# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'm6.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(373, 200)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(121, 32, 216, 25))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.t1 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.t1.setObjectName("t1")
        self.horizontalLayout.addWidget(self.t1)
        self.b1 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.b1.setObjectName("b1")
        self.horizontalLayout.addWidget(self.b1)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(112, 132, 216, 25))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.t2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.t2.setObjectName("t2")
        self.horizontalLayout_2.addWidget(self.t2)
        self.b2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.b2.setObjectName("b2")
        self.horizontalLayout_2.addWidget(self.b2)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(52, 32, 61, 16))
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(80, 60, 33, 16))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(52, 132, 52, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(70, 160, 34, 16))
        self.label_4.setObjectName("label_4")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(40, 90, 301, 20))
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.p1 = QtWidgets.QLabel(Form)
        self.p1.setGeometry(QtCore.QRect(121, 60, 100, 16))
        self.p1.setObjectName("p1")
        self.p2 = QtWidgets.QLabel(Form)
        self.p2.setGeometry(QtCore.QRect(112, 160, 100, 16))
        self.p2.setObjectName("p2")

        self.pr=0                      #price of one copy
        self.total=0                   #total amount

        self.b1.clicked.connect(self.searchbook) 
        self.b2.clicked.connect(self.calctotal)
        
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    #method to search the book. 
    def searchbook(self):
        db=sqlite3.connect("m6-3.db")
        cur=db.cursor()
        ttl=self.t1.text()
        sql="SELECT * FROM books WHERE title='"+ttl+"'"
        cur=db.cursor()
        cur.execute(sql)
        rec=cur.fetchone()
        if rec!=None:
            self.pr=rec[3]
            self.p1.setText("<html><head/><body><p><span style=\" font-size:10pt; color:#0000ff;\">Rs. "+str(self.pr)+"</span></p></body></html>")
        else:
            self.p1.setText("<html><head/><body><p><span style=\" font-size:10pt; color:#b40000;\">Book Not Found!!</span></p></body></html>")
            self.pr=0
            
    #method to calculate the total amount.        
    def calctotal(self):
        qty=int(self.t2.text())
        self.total=self.pr * qty
        self.p2.setText("<html><head/><body><p><span style=\" font-size:10pt; color:#0000ff;\">Rs. "+str(self.total)+"</span></p></body></html>")

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.b1.setText(_translate("Form", "Find Price"))
        self.b2.setText(_translate("Form", "Find Total"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">Book Title:</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">Price:</span></p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">Quantity:</span></p></body></html>"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">Total:</span></p></body></html>"))
        self.p1.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; color:#0000ff;\">Rs. 0</span></p></body></html>"))
        self.p2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; color:#0000ff;\">Rs. 0</span></p></body></html>"))

        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
