# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'open_win.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
myfantasy= sqlite3.connect("fantasy_cricket_DB.db")
cursfantasy=myfantasy.cursor()



class Ui_Open(object):
    def setupUi(self, Open):
        Open.setObjectName("Open")
        Open.resize(300, 93)
        Open.setMinimumSize(QtCore.QSize(300, 93))
        Open.setMaximumSize(QtCore.QSize(300, 93))
        self.label = QtWidgets.QLabel(Open)
        self.label.setGeometry(QtCore.QRect(70, 10, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.open_list = QtWidgets.QComboBox(Open)
        self.open_list.setGeometry(QtCore.QRect(70, 30, 201, 22))
        self.open_list.setObjectName("open_list")
        self.label_2 = QtWidgets.QLabel(Open)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 47, 51))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../icons/open-icon.png"))
        self.label_2.setObjectName("label_2")
        self.open_bt = QtWidgets.QPushButton(Open)
        self.open_bt.setGeometry(QtCore.QRect(190, 60, 75, 23))
        self.open_bt.setObjectName("open_bt")

        self.retranslateUi(Open)
        QtCore.QMetaObject.connectSlotsByName(Open)
        teams= cursfantasy.execute("SELECT DISTINCT name FROM teams;")  # fetching team names
        y= teams.fetchall()
        for i in y:
            self.open_list.addItem(i[0])

    def retranslateUi(self, Open):
        _translate = QtCore.QCoreApplication.translate
        Open.setWindowTitle(_translate("Open", "Open"))
        self.label.setText(_translate("Open", "Select  Team"))
        self.open_bt.setText(_translate("Open", "Open"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Open = QtWidgets.QDialog()
    ui = Ui_Open()
    ui.setupUi(Open)
    Open.show()
    sys.exit(app.exec_())

