# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'save.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_save_box(object):
    def setupUi(self, save_box):
        save_box.setObjectName("save_box")
        save_box.resize(300, 101)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(save_box.sizePolicy().hasHeightForWidth())
        save_box.setSizePolicy(sizePolicy)
        save_box.setMinimumSize(QtCore.QSize(300, 101))
        save_box.setMaximumSize(QtCore.QSize(300, 101))
        save_box.setStyleSheet("")
        self.label_2 = QtWidgets.QLabel(save_box)
        self.label_2.setGeometry(QtCore.QRect(9, 9, 16, 16))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.pushbutton = QtWidgets.QPushButton(save_box)
        self.pushbutton.setEnabled(True)
        self.pushbutton.setGeometry(QtCore.QRect(120, 60, 72, 21))
        self.pushbutton.setAutoFillBackground(False)
        self.pushbutton.setStyleSheet("")
        self.pushbutton.setText("OK")
        self.pushbutton.setIconSize(QtCore.QSize(60, 24))
        self.pushbutton.setAutoDefault(True)
        self.pushbutton.setDefault(False)
        self.pushbutton.setFlat(False)
        self.pushbutton.setObjectName("pushbutton")
        self.lable1 = QtWidgets.QLabel(save_box)
        self.lable1.setGeometry(QtCore.QRect(70, 10, 171, 41))
        self.lable1.setTextFormat(QtCore.Qt.AutoText)
        self.lable1.setWordWrap(False)
        self.lable1.setIndent(0)
        self.lable1.setObjectName("lable1")
        self.label_3 = QtWidgets.QLabel(save_box)
        self.label_3.setEnabled(True)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 51, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../icons/green-check-button.png"))
        self.label_3.setObjectName("label_3")
        self.label_2.raise_()
        self.lable1.raise_()
        self.label_3.raise_()
        self.pushbutton.raise_()

        self.retranslateUi(save_box)
        self.pushbutton.clicked.connect(save_box.close)
        QtCore.QMetaObject.connectSlotsByName(save_box)

    def retranslateUi(self, save_box):
        _translate = QtCore.QCoreApplication.translate
        save_box.setWindowTitle(_translate("save_box", "Saved"))
        self.lable1.setText(_translate("save_box", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Team successfully saved.</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    save_box = QtWidgets.QDialog()
    ui = Ui_save_box()
    ui.setupUi(save_box)
    save_box.show()
    sys.exit(app.exec_())
